// Code generated by Slice Machine. DO NOT EDIT.

import Projects from './Projects';
import Skills from './Skills';
import Tools from './Tools';

export {
	Projects,
	Skills,
	Tools,
};

export const components = {
	projects: Projects,
	skills: Skills,
	tools: Tools,
};
