// Code generated by Slice Machine. DO NOT EDIT.

import Skills from './Skills';
import Tools from './Tools';

export {
	Skills,
	Tools,
};

export const components = {
	skills: Skills,
	tools: Tools,
};
