// Code generated by Slice Machine. DO NOT EDIT.

import ProjectsList from './ProjectsList';
import Skills from './Skills';
import Tools from './Tools';

export {
	ProjectsList,
	Skills,
	Tools,
};

export const components = {
	projects_list: ProjectsList,
	skills: Skills,
	tools: Tools,
};
